
const express=require('express'),cookieParser=require('cookie-parser'),jwt=require('jsonwebtoken'),bcrypt=require('bcryptjs'),crypto=require('crypto');
const {Pool}=require('pg'); const app=express();
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false});
const PORT=process.env.PORT||3000, JWT_SECRET=process.env.JWT_SECRET||'local-dev-secret';
app.use(express.json({limit:'1mb'})); app.use(cookieParser()); app.use(express.static(__dirname));
const id=()=>crypto.randomUUID(), invite=()=>crypto.randomBytes(3).toString('hex').toUpperCase();
const sign=u=>jwt.sign({id:u.id,household_id:u.household_id},JWT_SECRET,{expiresIn:'30d'});
const safe=u=>({id:u.id,household_id:u.household_id,name:u.name,username:u.username,color:u.color});
async function init(){
 await pool.query(`CREATE TABLE IF NOT EXISTS households(id uuid PRIMARY KEY,name text NOT NULL,invite_code text UNIQUE NOT NULL,timezone text NOT NULL DEFAULT 'America/Indiana/Indianapolis',created_at timestamptz DEFAULT now())`);
 await pool.query(`CREATE TABLE IF NOT EXISTS users(id uuid PRIMARY KEY,household_id uuid REFERENCES households(id) ON DELETE CASCADE,name text NOT NULL,username text UNIQUE NOT NULL,password_hash text NOT NULL,color text NOT NULL DEFAULT '#2563eb',created_at timestamptz DEFAULT now())`);
 await pool.query(`CREATE TABLE IF NOT EXISTS tasks(id uuid PRIMARY KEY,household_id uuid REFERENCES households(id) ON DELETE CASCADE,title text NOT NULL,notes text DEFAULT '',type text NOT NULL DEFAULT 'task',owner_id uuid REFERENCES users(id) ON DELETE SET NULL,assigned_by uuid REFERENCES users(id) ON DELETE SET NULL,due_at timestamptz,start_at timestamptz,end_at timestamptz,category text DEFAULT 'Household',priority text DEFAULT 'Normal',recurrence text DEFAULT 'None',complete boolean DEFAULT false,completed_at timestamptz,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now())`);
 await pool.query(`CREATE TABLE IF NOT EXISTS accounts(id uuid PRIMARY KEY,household_id uuid REFERENCES households(id) ON DELETE CASCADE,name text NOT NULL,type text DEFAULT 'Checking',starting_balance numeric DEFAULT 0,created_at timestamptz DEFAULT now())`);
 await pool.query(`CREATE TABLE IF NOT EXISTS transactions(id uuid PRIMARY KEY,household_id uuid REFERENCES households(id) ON DELETE CASCADE,account_id uuid REFERENCES accounts(id) ON DELETE SET NULL,date date NOT NULL,merchant text NOT NULL,category text NOT NULL DEFAULT 'General',amount numeric NOT NULL,kind text NOT NULL CHECK(kind IN ('income','expense')),notes text DEFAULT '',created_by uuid REFERENCES users(id) ON DELETE SET NULL,created_at timestamptz DEFAULT now())`);
 await pool.query(`CREATE TABLE IF NOT EXISTS budgets(id uuid PRIMARY KEY,household_id uuid REFERENCES households(id) ON DELETE CASCADE,category text NOT NULL,monthly_limit numeric NOT NULL,created_at timestamptz DEFAULT now(),UNIQUE(household_id,category))`);
}
init().catch(e=>{console.error(e);process.exit(1)});
async function auth(req,res,next){try{const token=req.cookies.token||(req.headers.authorization||'').replace('Bearer ','');if(!token)return res.status(401).json({error:'Not logged in'});const data=jwt.verify(token,JWT_SECRET);const {rows}=await pool.query('SELECT * FROM users WHERE id=$1',[data.id]);if(!rows[0])return res.status(401).json({error:'User not found'});req.user=rows[0];next()}catch(e){res.status(401).json({error:'Session expired'})}}
app.get('/api/health',(req,res)=>res.json({ok:true}));
app.post('/api/auth/create-household',async(req,res)=>{const {householdName,name,username,password,color}=req.body;if(!householdName||!name||!username||!password)return res.status(400).json({error:'All fields required'});const hId=id(),uId=id(),code=invite(),hash=await bcrypt.hash(password,10),client=await pool.connect();try{await client.query('BEGIN');await client.query('INSERT INTO households(id,name,invite_code) VALUES($1,$2,$3)',[hId,householdName.trim(),code]);const {rows}=await client.query('INSERT INTO users(id,household_id,name,username,password_hash,color) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[uId,hId,name.trim(),username.trim().toLowerCase(),hash,color||'#2563eb']);await client.query('COMMIT');res.cookie('token',sign(rows[0]),{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:2592000000});res.json({user:safe(rows[0])})}catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.code==='23505'?'Username already exists':'Could not create household'})}finally{client.release()}});
app.post('/api/auth/join',async(req,res)=>{const {inviteCode,name,username,password,color}=req.body;if(!inviteCode||!name||!username||!password)return res.status(400).json({error:'All fields required'});const {rows:h}=await pool.query('SELECT * FROM households WHERE invite_code=$1',[String(inviteCode).trim().toUpperCase()]);if(!h[0])return res.status(404).json({error:'Invite code not found'});try{const hash=await bcrypt.hash(password,10);const {rows}=await pool.query('INSERT INTO users(id,household_id,name,username,password_hash,color) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[id(),h[0].id,name.trim(),username.trim().toLowerCase(),hash,color||'#7c3aed']);res.cookie('token',sign(rows[0]),{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:2592000000});res.json({user:safe(rows[0])})}catch(e){res.status(400).json({error:e.code==='23505'?'Username already exists':'Could not join household'})}});
app.post('/api/auth/login',async(req,res)=>{const username=String(req.body.username||'').trim().toLowerCase(),password=String(req.body.password||'');const {rows}=await pool.query('SELECT * FROM users WHERE username=$1',[username]);if(!rows[0]||!(await bcrypt.compare(password,rows[0].password_hash)))return res.status(401).json({error:'Wrong username or password'});res.cookie('token',sign(rows[0]),{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:2592000000});res.json({user:safe(rows[0])})});
app.post('/api/auth/logout',(req,res)=>{res.clearCookie('token');res.json({ok:true})});
app.get('/api/bootstrap',auth,async(req,res)=>{const hid=req.user.household_id;const household=(await pool.query('SELECT * FROM households WHERE id=$1',[hid])).rows[0];const members=(await pool.query('SELECT id,name,username,color FROM users WHERE household_id=$1 ORDER BY created_at',[hid])).rows;const tasks=(await pool.query('SELECT * FROM tasks WHERE household_id=$1 ORDER BY COALESCE(due_at,start_at,created_at),created_at DESC',[hid])).rows;const accounts=(await pool.query('SELECT * FROM accounts WHERE household_id=$1 ORDER BY created_at',[hid])).rows;const transactions=(await pool.query('SELECT * FROM transactions WHERE household_id=$1 ORDER BY date DESC,created_at DESC LIMIT 300',[hid])).rows;const budgets=(await pool.query('SELECT * FROM budgets WHERE household_id=$1 ORDER BY category',[hid])).rows;res.json({user:safe(req.user),household,members,tasks,accounts,transactions,budgets})});
app.patch('/api/household',auth,async(req,res)=>{const name=String(req.body.name||'').trim(),timezone=String(req.body.timezone||'America/Indiana/Indianapolis').trim();if(!name)return res.status(400).json({error:'Household name required'});try{new Intl.DateTimeFormat('en-US',{timeZone:timezone}).format(new Date())}catch{return res.status(400).json({error:'Invalid time zone'})}const {rows}=await pool.query('UPDATE households SET name=$1,timezone=$2 WHERE id=$3 RETURNING *',[name,timezone,req.user.household_id]);res.json(rows[0])});
app.post('/api/household/rotate-invite',auth,async(req,res)=>{const {rows}=await pool.query('UPDATE households SET invite_code=$1 WHERE id=$2 RETURNING *',[invite(),req.user.household_id]);res.json(rows[0])});
app.post('/api/tasks',auth,async(req,res)=>{const b=req.body;if(!b.title)return res.status(400).json({error:'Title required'});const {rows}=await pool.query(`INSERT INTO tasks(id,household_id,title,notes,type,owner_id,assigned_by,due_at,start_at,end_at,category,priority,recurrence,complete) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,false) RETURNING *`,[id(),req.user.household_id,b.title.trim(),b.notes||'',b.type||'task',b.owner_id||null,req.user.id,b.due_at||null,b.start_at||null,b.end_at||null,b.category||'Household',b.priority||'Normal',b.recurrence||'None']);res.json(rows[0])});
app.post('/api/tasks/:id/toggle',auth,async(req,res)=>{const {rows}=await pool.query(`UPDATE tasks SET complete=NOT complete,completed_at=CASE WHEN NOT complete THEN now() ELSE null END,updated_at=now() WHERE id=$1 AND household_id=$2 RETURNING *`,[req.params.id,req.user.household_id]);if(!rows[0])return res.status(404).json({error:'Not found'});res.json(rows[0])});
app.delete('/api/tasks/:id',auth,async(req,res)=>{await pool.query('DELETE FROM tasks WHERE id=$1 AND household_id=$2',[req.params.id,req.user.household_id]);res.json({ok:true})});
app.post('/api/accounts',auth,async(req,res)=>{const {name,type,starting_balance}=req.body;if(!name)return res.status(400).json({error:'Account name required'});const {rows}=await pool.query('INSERT INTO accounts(id,household_id,name,type,starting_balance) VALUES($1,$2,$3,$4,$5) RETURNING *',[id(),req.user.household_id,name.trim(),type||'Checking',Number(starting_balance||0)]);res.json(rows[0])});
app.post('/api/transactions',auth,async(req,res)=>{const b=req.body;if(!b.date||!b.merchant||!b.amount)return res.status(400).json({error:'Date, merchant, and amount required'});const kind=b.kind==='income'?'income':'expense';const {rows}=await pool.query(`INSERT INTO transactions(id,household_id,account_id,date,merchant,category,amount,kind,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[id(),req.user.household_id,b.account_id||null,b.date,b.merchant.trim(),b.category||'General',Math.abs(Number(b.amount)),kind,b.notes||'',req.user.id]);res.json(rows[0])});
app.delete('/api/transactions/:id',auth,async(req,res)=>{await pool.query('DELETE FROM transactions WHERE id=$1 AND household_id=$2',[req.params.id,req.user.household_id]);res.json({ok:true})});
app.post('/api/budgets',auth,async(req,res)=>{const {category,monthly_limit}=req.body;if(!category||!monthly_limit)return res.status(400).json({error:'Category and monthly limit required'});const {rows}=await pool.query(`INSERT INTO budgets(id,household_id,category,monthly_limit) VALUES($1,$2,$3,$4) ON CONFLICT(household_id,category) DO UPDATE SET monthly_limit=excluded.monthly_limit RETURNING *`,[id(),req.user.household_id,category.trim(),Number(monthly_limit)]);res.json(rows[0])});
app.delete('/api/budgets/:id',auth,async(req,res)=>{await pool.query('DELETE FROM budgets WHERE id=$1 AND household_id=$2',[req.params.id,req.user.household_id]);res.json({ok:true})});
app.listen(PORT,()=>console.log('HouseBoard running on '+PORT));
